/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DressListing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'color' : IDL.Text,
  'size' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'sellerId' : IDL.Principal,
  'price' : IDL.Nat,
  'photos' : IDL.Vec(ExternalBlob),
  'condition' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const Message = IDL.Record({
  'listingId' : IDL.Nat,
  'message' : IDL.Text,
  'buyerId' : IDL.Principal,
  'sellerId' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteListing' : IDL.Func([IDL.Nat], [], []),
  'filterByColor' : IDL.Func([IDL.Text], [IDL.Vec(DressListing)], ['query']),
  'filterByCondition' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DressListing)],
      ['query'],
    ),
  'filterByPrice' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(DressListing)],
      ['query'],
    ),
  'filterBySize' : IDL.Func([IDL.Text], [IDL.Vec(DressListing)], ['query']),
  'getAllListings' : IDL.Func([], [IDL.Vec(DressListing)], ['query']),
  'getAvailableListings' : IDL.Func([], [IDL.Vec(DressListing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedListings' : IDL.Func([], [IDL.Vec(DressListing)], ['query']),
  'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(DressListing)], ['query']),
  'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getSellerListings' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DressListing)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'promoteListing' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchListings' : IDL.Func([IDL.Text], [IDL.Vec(DressListing)], ['query']),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
  'updateListing' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DressListing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'color' : IDL.Text,
    'size' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'sellerId' : IDL.Principal,
    'price' : IDL.Nat,
    'photos' : IDL.Vec(ExternalBlob),
    'condition' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const Message = IDL.Record({
    'listingId' : IDL.Nat,
    'message' : IDL.Text,
    'buyerId' : IDL.Principal,
    'sellerId' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteListing' : IDL.Func([IDL.Nat], [], []),
    'filterByColor' : IDL.Func([IDL.Text], [IDL.Vec(DressListing)], ['query']),
    'filterByCondition' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DressListing)],
        ['query'],
      ),
    'filterByPrice' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(DressListing)],
        ['query'],
      ),
    'filterBySize' : IDL.Func([IDL.Text], [IDL.Vec(DressListing)], ['query']),
    'getAllListings' : IDL.Func([], [IDL.Vec(DressListing)], ['query']),
    'getAvailableListings' : IDL.Func([], [IDL.Vec(DressListing)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedListings' : IDL.Func([], [IDL.Vec(DressListing)], ['query']),
    'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(DressListing)], ['query']),
    'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getSellerListings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DressListing)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'promoteListing' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchListings' : IDL.Func([IDL.Text], [IDL.Vec(DressListing)], ['query']),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
    'updateListing' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };